name: Code Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Setup Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.15.0
          run_install: true
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Check code format
        run: pnpm run format-check
      - name: Typecheck
        run: pnpm run typecheck
